# https://mise.jdx.dev/configuration.html
[tools]
ruby = "3.4.8"
nodejs = "20.9.0"
yarn = "1.22.19"
python = "3.11"
postgres = "15.4"
go = "1.23.1"
redis = "7.2.3"
node = "22.11.0"
"npm:prettier" = "latest"
"npm:markdownlint-cli" = "latest"
uv = "latest"
usage = "latest"
"npm:@github/copilot" = "latest"
"npm:linearis" = "latest"
"npm:@vscode/vsce" = "latest"
yq = "latest"

[env]

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
python.uv_venv_auto = true
